const products = [
    {
        _id: "1",
        name: "Airpods Wireless Bluetooth Headphones",
        image: "/images/airpods.jpg",
        description:
            "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
        link: "https://www.amazon.com/Apple-AirPods-Charging-Previous-Model/dp/B01MQWUXZS/ref=sr_1_1_sspa?dchild=1&keywords=airpods&nav_sdd=aps&pd_rd_r=649b7e68-b22a-4f26-8d45-cdcf7b7b6173&pd_rd_w=y35Mq&pd_rd_wg=8MuAj&pf_rd_p=1dc0c6f9-9a3c-4876-bf37-8a618b58d2fd&pf_rd_r=24T0CQZX2JGK08CCXV5F&qid=1630335367&s=aht&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFXT0VHWFpZRk1CUlMmZW5jcnlwdGVkSWQ9QTAzMTYzOTYyOEdPTDdZRjJaVzlVJmVuY3J5cHRlZEFkSWQ9QTA1ODAxNjExUlJSTERVMTVHWDZCJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==\n",
    },
    {
        _id: "2",
        name: "iPhone 11 Pro 256GB Memory",
        image: "/images/phone.jpg",
        description:
            "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
        brand: "Apple",
        category: "Electronics",
        price: 599.99,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
        link: "https://www.amazon.com/Apple-iPhone-256GB-Unlocked-Renewed/dp/B07ZQRL9XY\n",
    },
    {
        _id: "3",
        name: "Cannon EOS 80D DSLR Camera",
        image: "/images/camera.jpg",
        description:
            "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
        brand: "Cannon",
        category: "Electronics",
        price: 929.99,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
        link: "https://www.amazon.com/Canon-Digital-Camera-Megapixel-Sensor/dp/B01BUYK04A\n",
    },
    {
        _id: "4",
        name: "Sony Playstation 4 Pro White Version",
        image: "/images/playstation.jpg",
        description:
            "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
        brand: "Sony",
        category: "Electronics",
        price: 399.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
        link: "https://www.amazon.com/Sony-PlayStation-Pro-1TB-White-4/dp/B07MLWLYCN\n",
    },
    {
        _id: "5",
        name: "Logitech G-Series Gaming Mouse",
        image: "/images/mouse.jpg",
        description:
            "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
        brand: "Logitech",
        category: "Electronics",
        price: 49.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
        link: "https://www.amazon.com/Logitech-Wireless-Gaming-Esports-Performance/dp/B07GCKQD77\n",
    },
    {
        _id: "6",
        name: "Amazon Echo Dot 3rd Generation",
        image: "/images/alexa.jpg",
        description:
            "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
        brand: "Amazon",
        category: "Electronics",
        price: 29.99,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
        link: "https://www.amazon.com/Echo-Dot/dp/B07FZ8S74R\n",
    },
];

export default products;
